import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import News from "./components/News";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex justify-between max-w-6xl mx-auto">

        <div className="hidden sm:inline border-r border-gray-200 h-screen">
          <Sidebar />
        </div>

        <div className="">
          {children}
        </div>

        <div className="lg:flex-col p-3 h-screen border-l hidden lg:flex w-[24rem]">
          <div className="sticky top-0 bg-white py-2">
            <input
              type="text"
              placeholder="Search"
              className="border border-gray-200 rounded-3xl bg-gray-100 
              text-sm w-full px-4 py-2">

              </input>
          </div>
          <News />
        </div>

        </div>
      </body>
    </html>
  );
}
